PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_inspections` (
	`id` text PRIMARY KEY NOT NULL,
	`tenant_id` text NOT NULL,
	`inspector_id` text,
	`property_address` text NOT NULL,
	`address_place_id` text,
	`address_street` text,
	`address_city` text,
	`address_state` text,
	`address_zip` text,
	`address_county` text,
	`address_lat` real,
	`address_lng` real,
	`address_geocoded_at` integer,
	`template_id` text,
	`date` text NOT NULL,
	`status` text DEFAULT 'requested' NOT NULL,
	`report_status` text DEFAULT 'in_progress' NOT NULL,
	`payment_status` text DEFAULT 'unpaid' NOT NULL,
	`price_cents` integer DEFAULT 0 NOT NULL,
	`created_at` integer NOT NULL,
	`confirmed_at` integer,
	`cancel_reason` text,
	`cancel_notes` text,
	`is_payment_required` integer DEFAULT false NOT NULL,
	`is_agreement_required` integer DEFAULT false NOT NULL,
	`is_auto_sign_on_publish` integer DEFAULT false NOT NULL,
	`discount_code_id` text,
	`discount_amount_cents` integer,
	`closing_date` text,
	`referral_source` text,
	`reference_number` text,
	`internal_notes` text,
	`year_built` integer,
	`sqft` integer,
	`foundation_type` text,
	`bedrooms` integer,
	`bathrooms` real,
	`lot_size` text,
	`property_facts` text,
	`cover_photo_id` text,
	`cover_crop` text,
	`cover_image_key` text,
	`unit` text,
	`property_type` text,
	`commercial_subtype` text,
	`report_tier` text,
	`county` text,
	`is_automations_disabled` integer DEFAULT false NOT NULL,
	`template_snapshot` text,
	`template_snapshot_version` integer DEFAULT 1,
	`report_theme_override` text,
	`require_defect_fields_override` text,
	`request_id` text,
	`concierge_status` text,
	`is_team_mode` integer DEFAULT false NOT NULL,
	`lead_inspector_id` text,
	`helper_inspector_ids` text DEFAULT '[]' NOT NULL,
	`data_version` integer DEFAULT 0 NOT NULL,
	`source_inspection_id` text,
	`root_inspection_id` text,
	`reinspection_round` integer,
	`unit_inspection_mode` text DEFAULT 'tagged' NOT NULL,
	`location_options` text,
	`sampling_declaration` text,
	`pca_narrative` text,
	`deviations` text,
	`report_photo_mode` text,
	`scheduled_start_ms` integer,
	`scheduled_end_ms` integer,
	`duration_min` integer,
	FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`inspector_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`template_id`) REFERENCES `templates`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`discount_code_id`) REFERENCES `discount_codes`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`request_id`) REFERENCES `inspection_requests`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
INSERT INTO `__new_inspections`("id", "tenant_id", "inspector_id", "property_address", "address_place_id", "address_street", "address_city", "address_state", "address_zip", "address_county", "address_lat", "address_lng", "address_geocoded_at", "template_id", "date", "status", "report_status", "payment_status", "price_cents", "created_at", "confirmed_at", "cancel_reason", "cancel_notes", "is_payment_required", "is_agreement_required", "is_auto_sign_on_publish", "discount_code_id", "discount_amount_cents", "closing_date", "referral_source", "reference_number", "internal_notes", "year_built", "sqft", "foundation_type", "bedrooms", "bathrooms", "lot_size", "property_facts", "cover_photo_id", "cover_crop", "cover_image_key", "unit", "property_type", "commercial_subtype", "report_tier", "county", "is_automations_disabled", "template_snapshot", "template_snapshot_version", "report_theme_override", "require_defect_fields_override", "request_id", "concierge_status", "is_team_mode", "lead_inspector_id", "helper_inspector_ids", "data_version", "source_inspection_id", "root_inspection_id", "reinspection_round", "unit_inspection_mode", "location_options", "sampling_declaration", "pca_narrative", "deviations", "report_photo_mode", "scheduled_start_ms", "scheduled_end_ms", "duration_min") SELECT "id", "tenant_id", "inspector_id", "property_address", "address_place_id", "address_street", "address_city", "address_state", "address_zip", "address_county", "address_lat", "address_lng", "address_geocoded_at", "template_id", "date", "status", "report_status", "payment_status", "price_cents", "created_at", "confirmed_at", "cancel_reason", "cancel_notes", "is_payment_required", "is_agreement_required", "is_auto_sign_on_publish", "discount_code_id", "discount_amount_cents", "closing_date", "referral_source", "reference_number", "internal_notes", "year_built", "sqft", "foundation_type", "bedrooms", "bathrooms", "lot_size", "property_facts", "cover_photo_id", "cover_crop", "cover_image_key", "unit", "property_type", "commercial_subtype", "report_tier", "county", "is_automations_disabled", "template_snapshot", "template_snapshot_version", "report_theme_override", "require_defect_fields_override", "request_id", "concierge_status", "is_team_mode", "lead_inspector_id", "helper_inspector_ids", "data_version", "source_inspection_id", "root_inspection_id", "reinspection_round", "unit_inspection_mode", "location_options", "sampling_declaration", "pca_narrative", "deviations", "report_photo_mode", "scheduled_start_ms", "scheduled_end_ms", "duration_min" FROM `inspections`;--> statement-breakpoint
DROP TABLE `inspections`;--> statement-breakpoint
ALTER TABLE `__new_inspections` RENAME TO `inspections`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE INDEX `idx_inspections_tenant` ON `inspections` (`tenant_id`);--> statement-breakpoint
CREATE INDEX `idx_inspections_request` ON `inspections` (`request_id`);--> statement-breakpoint
CREATE INDEX `idx_inspections_inspector` ON `inspections` (`inspector_id`);--> statement-breakpoint
CREATE INDEX `idx_inspections_tenant_status` ON `inspections` (`tenant_id`,`status`);--> statement-breakpoint
CREATE INDEX `idx_inspections_tenant_date` ON `inspections` (`tenant_id`,`date`);--> statement-breakpoint
CREATE INDEX `idx_inspections_inspector_date` ON `inspections` (`inspector_id`,`date`);--> statement-breakpoint
CREATE INDEX `idx_inspections_root` ON `inspections` (`root_inspection_id`);