import {
  type RouteConfig,
  index,
  route,
  layout,
} from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("login", "routes/login.tsx"),
  route("logout", "routes/logout.tsx"),
  // Full-screen editor (own chrome, no sidebar)
  route("inspections/:id/edit", "routes/inspection-edit.tsx"),
  route("templates/:id/edit", "routes/template-edit.tsx"),
  // Public pages — no auth, minimal layout, SSR for SEO
  layout("routes/public-layout.tsx", [
    route("book/:tenant/:slug", "routes/public/booking.tsx"),
    route("report/:tenant/:id", "routes/public/report.tsx"),
    route(
      "agreements/sign/:tenant/:token",
      "routes/public/agreement-sign.tsx",
    ),
    route("r/:id/invoice", "routes/public/invoice.tsx"),
    route("verify/:envelopeId", "routes/public/verify.tsx"),
    route("verify", "routes/public/verify-offline.tsx"),
    route("v/:token", "routes/public/verify-token.tsx"),
    route("observe/inspections/:id", "routes/public/observe.tsx"),
    route(
      "concierge/book/:tenant/:slug",
      "routes/public/concierge-book.tsx",
    ),
    route("concierge/confirm", "routes/public/concierge-confirm.tsx"),
    route("concierge/expired", "routes/public/concierge-expired.tsx"),
    route(
      "inspector/:tenant/:slug",
      "routes/public/inspector-profile.tsx",
    ),
    route("inspector-not-found", "routes/public/inspector-not-found.tsx"),
    route(
      "report-gate/:tenant/:id",
      "routes/public/report-gate.tsx",
    ),
    route(
      "report-view/:tenant/:id",
      "routes/public/report-card-stack.tsx",
    ),
    route("messages/:token", "routes/public/messages.tsx"),
    route("r/:id/repair-request", "routes/public/repair-request.tsx"),
    route(
      "agreements/print/:token",
      "routes/public/agreement-printable.tsx",
    ),
  ]),
  // Standalone pages (own chrome, no sidebar)
  route("setup", "routes/setup.tsx"),
  route("inspections/:id/form", "routes/form-renderer.tsx"),
  route("join/:token", "routes/join.tsx"),
  route("guest-join/:token", "routes/guest-join.tsx"),
  route("conflict-resolver/:id", "routes/conflict-resolver.tsx"),
  route("version-diff/:id", "routes/version-diff.tsx"),
  // Standalone public — no layout (iframe-friendly)
  route(
    "embed/:tenant/:slug",
    "routes/public/booking-embed.tsx",
  ),
  // Standalone agent pages — no agent-layout chrome
  route("agent-invite/:token", "routes/agent/invite-accept.tsx"),
  route("agent-invite-expired", "routes/agent/invite-expired.tsx"),
  // Error / utility pages (bare, outside auth)
  route("not-found", "routes/not-found.tsx"),
  route("feature-disabled", "routes/feature-disabled.tsx"),
  // API docs (Swagger UI) — was hono GET /ui; OpenAPI JSON still served at /doc
  route("ui", "routes/docs.tsx"),
  layout("routes/auth-layout.tsx", [
    route("dashboard", "routes/dashboard.tsx"),
    route("calendar", "routes/calendar.tsx"),
    route("contacts", "routes/contacts.tsx"),
    route("invoices", "routes/invoices.tsx"),
    route("notifications", "routes/notifications.tsx"),
    route("templates", "routes/templates.tsx"),
    route("team", "routes/team.tsx"),
    route("metrics", "routes/metrics.tsx"),
    route("apprentice-review", "routes/apprentice-review.tsx"),
    route("reports", "routes/reports.tsx"),
    layout("routes/settings-layout.tsx", [
      route("settings", "routes/settings-hub.tsx"),
      route("settings/profile", "routes/settings-profile.tsx"),
      route("settings/inspection", "routes/settings-inspection.tsx"),
      route("settings/workspace", "routes/settings-workspace.tsx"),
      route("settings/services", "routes/settings-services.tsx"),
      route("settings/communication", "routes/settings-communication.tsx"),
      route("settings/automations", "routes/settings-automations.tsx"),
      route("settings/data", "routes/settings-data.tsx"),
      route("settings/widget", "routes/settings-widget.tsx"),
      route("settings/account", "routes/settings-account.tsx"),
      route("settings/advanced", "routes/settings-advanced.tsx"),
      route("settings/integrations", "routes/settings-integrations.tsx"),
      route("settings/integrations/qbo", "routes/settings-integrations-qbo.tsx"),
      route("settings/event-types", "routes/settings-event-types.tsx"),
      route("settings/inspection-types", "routes/settings-inspection-types.tsx"),
      route("settings/booking", "routes/settings-booking.tsx"),
      route("settings/catalog/booking", "routes/settings-catalog-booking.tsx"),
      route("settings/billing", "routes/settings-billing.tsx"),
      route("settings/security", "routes/settings-security.tsx"),
    ]),
    route("comments", "routes/comments.tsx"),
    route("recommendations", "routes/recommendations.tsx"),
    route("library/tags", "routes/library/tags.tsx"),
    route("agreements", "routes/agreements.tsx"),
    route("library/rating-systems", "routes/library/rating-systems.tsx"),
    route("marketplace", "routes/marketplace.tsx"),
  ]),
  layout("routes/agent-layout.tsx", [
    route("agent-dashboard", "routes/agent/dashboard.tsx"),
    route("agent-settings/profile", "routes/agent/settings-profile.tsx"),
    route("agent-inspectors", "routes/agent/inspectors.tsx"),
    route("agent-recommendations", "routes/agent/recommendations.tsx"),
    route("agent-signup", "routes/agent/signup.tsx"),
  ]),
] satisfies RouteConfig;
