/* eslint-disable @typescript-eslint/no-explicit-any, no-console */
/**
 * Codemod: backfill MCP/Skill route metadata across every createRoute() in
 * server/api/*.ts. Idempotent — re-running is a no-op for already-wrapped routes.
 *
 * What it does for each `createRoute({...})`:
 *  1. Skip if already wrapped with `withMcpMetadata(...)`.
 *  2. Derive operationId (camelCase) from method + path + filename if missing.
 *  3. Normalize tags to lowercase + map to the controlled vocabulary.
 *  4. Pick x-scopes from method + path heuristics.
 *  5. Pick x-tier — default 'extended'; mark webhooks/M2M/sysadmin 'excluded'
 *     and a curated CRUD shortlist 'primary'.
 *  6. Wrap the createRoute call: `createRoute(withMcpMetadata({...}, { ... }))`.
 *  7. Add `import { withMcpMetadata } from '../lib/route-metadata-standards';`
 *     if missing.
 *
 * Does NOT touch:
 *  - summary / description (quality work — left for a manual or LLM pass)
 *  - Zod schemas (separate codemod handles `.describe()` injection)
 *  - handlers
 *
 * Writes `scripts/backfill-route-metadata.report.md` listing each route's
 * decisions + flagging where summary < 4 words or description < 50 chars so
 * humans can do a targeted quality pass.
 *
 * Usage:
 *   npx tsx scripts/backfill-route-metadata.ts            # all api files
 *   npx tsx scripts/backfill-route-metadata.ts --dry-run  # report only
 *   npx tsx scripts/backfill-route-metadata.ts auth.ts    # one file
 */
import { Project } from 'ts-morph';
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import type { RouteAction } from './lib/route-metadata-types';
import { processFile } from './lib/route-metadata-ast';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ──────────────────────────────────────────────────────────────────
// Entry point
// ──────────────────────────────────────────────────────────────────

async function main() {
    const argv = process.argv.slice(2);
    const dryRun = argv.includes('--dry-run');
    const fileFilter = argv.filter(a => !a.startsWith('--'));

    const repoRoot = path.resolve(__dirname, '..');
    const apiDir = path.join(repoRoot, 'src', 'api');
    const tsConfig = path.join(repoRoot, 'tsconfig.json');

    const project = new Project({ tsConfigFilePath: tsConfig });

    const apiFiles = fs.readdirSync(apiDir)
        .filter(f => f.endsWith('.ts'))
        .filter(f => fileFilter.length === 0 || fileFilter.includes(f))
        .sort();

    const allActions: RouteAction[] = [];

    for (const file of apiFiles) {
        const full = path.join(apiDir, file);
        const sf = project.addSourceFileAtPath(full);
        const before = sf.getFullText();
        const actions = processFile(sf, file, dryRun);
        const after = sf.getFullText();

        if (!dryRun && after !== before) {
            sf.saveSync();
        }
        if (actions.length) {
            allActions.push(...actions);
            console.log(`${file}: ${actions.length} route${actions.length > 1 ? 's' : ''}${dryRun ? ' (dry-run)' : ''}`);
        }
    }

    // Write report
    const reportPath = path.join(repoRoot, 'scripts', 'backfill-route-metadata.report.md');
    const lines: string[] = [];
    lines.push('# Route metadata backfill report');
    lines.push('');
    lines.push(`Generated by \`scripts/backfill-route-metadata.ts\` on ${new Date().toISOString()}.`);
    lines.push('');
    lines.push(`Total routes processed: **${allActions.length}**.`);
    const primaryCount = allActions.filter(a => a.tier === 'primary').length;
    const extendedCount = allActions.filter(a => a.tier === 'extended').length;
    const excludedCount = allActions.filter(a => a.tier === 'excluded').length;
    lines.push(`Tier distribution: primary=${primaryCount} extended=${extendedCount} excluded=${excludedCount}.`);
    lines.push('');
    lines.push('## Routes needing human follow-up');
    lines.push('');
    lines.push('Each route below has at least one of:');
    lines.push('- `summary` outside 4-12 words OR ending with period');
    lines.push('- `description` shorter than 50 chars');
    lines.push('');
    lines.push('| File | Method | Path | operationId | sumFlag | descFlag | Current summary | Current description |');
    lines.push('|---|---|---|---|:-:|:-:|---|---|');
    for (const a of allActions) {
        if (!a.summaryFlag && !a.descriptionFlag) continue;
        const sCell = (a.summary || '(empty)').replaceAll('|', '\\|').slice(0, 60);
        const dCell = (a.description || '(empty)').replaceAll('|', '\\|').slice(0, 80);
        lines.push(`| ${a.file} | ${a.method} | \`${a.path}\` | \`${a.operationId}\` | ${a.summaryFlag ? '⚠' : ''} | ${a.descriptionFlag ? '⚠' : ''} | ${sCell} | ${dCell} |`);
    }
    lines.push('');
    lines.push('## All processed routes');
    lines.push('');
    lines.push('| File | Method | Path | operationId | tags | scopes | tier |');
    lines.push('|---|---|---|---|---|---|---|');
    for (const a of allActions) {
        lines.push(`| ${a.file} | ${a.method} | \`${a.path}\` | \`${a.operationId}\` | ${a.tags.join(', ')} | ${a.scopes.join(', ') || '(none)'} | ${a.tier} |`);
    }
    fs.writeFileSync(reportPath, lines.join('\n'));
    console.log(`\nReport written: ${reportPath}`);
    console.log(`Total: ${allActions.length} routes (${primaryCount} primary, ${extendedCount} extended, ${excludedCount} excluded)`);
    const flagged = allActions.filter(a => a.summaryFlag || a.descriptionFlag).length;
    console.log(`Flagged for human review: ${flagged} routes`);
    if (dryRun) console.log('Dry-run — no files were modified.');
}

main().catch(err => { console.error(err); process.exit(1); });
